/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package facturacion;

import java.text.DateFormat;
import java.text.Format;
import java.text.SimpleDateFormat;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Luis
 */
public class frmTaxiR extends javax.swing.JFrame {

    /**
     * Creates new form frmTaxiP
     */
    public frmTaxiR() {
        initComponents();
        this.setLocationRelativeTo(null);
        cmbNombreTaxi.setModel(frmChoferes.modeloChoferes);
        cmbOrigenT.setModel(modeloBarriosOrigen);
        cmbDestinoT.setModel(modeloBarriosDestino);
        
        
        //Barrios Origen
        modeloBarriosOrigen.addElement("Los Cauquenes");
        modeloBarriosOrigen.addElement("Mision Alta");
        modeloBarriosOrigen.addElement("Mision Baja");
        modeloBarriosOrigen.addElement("San Martin");
        modeloBarriosOrigen.addElement("Rio Pipo");
        
        //Barrio Destino
        modeloBarriosDestino.addElement("Los Cauquenes");
        modeloBarriosDestino.addElement("Mision Alta");
        modeloBarriosDestino.addElement("Mision Baja");
        modeloBarriosDestino.addElement("San Martin");
        modeloBarriosDestino.addElement("Rio Pipo");
        
        cmbOrigenT.setSelectedIndex(-1);
        cmbDestinoT.setSelectedIndex(-1);
        cmbNombreTaxi.setSelectedIndex(-1);
        
        //Formato de tiempo
        Format tiempo=new SimpleDateFormat("HH:mm");
        

        // Arreglar cant de autos. Poner formato de hora en caja de texto
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelTaxiR = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtNombreT = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmbOrigenT = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        txtDireccionOrigenT = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtTelefonoT = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cmbDestinoT = new javax.swing.JComboBox();
        txtDireccionDestinoT = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCntAutos = new com.toedter.components.JSpinField();
        PanelHorario = new javax.swing.JPanel();
        lblHora = new javax.swing.JLabel();
        txtHora = new javax.swing.JFormattedTextField();
        PanelTaxiP = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        cmbNombreTaxi = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        btnGuardarT = new javax.swing.JButton();
        btnSalirT = new javax.swing.JButton();

        setTitle("Reservado de Taxi");

        PanelTaxiR.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del Pasajero", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Nombre del Pasajero:");

        txtNombreT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Barrio de Origen:");

        cmbOrigenT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbOrigenT.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Direccion:");

        txtDireccionOrigenT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Telefono de contacto:");

        txtTelefonoT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Barrio de Destino:");

        cmbDestinoT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbDestinoT.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtDireccionDestinoT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Direccion:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Cantidad de autos:");

        PanelHorario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Horario:", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(204, 0, 0))); // NOI18N

        lblHora.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblHora.setText("Hora de recojida:");

        try {
            txtHora.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtHora.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHora.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelHorarioLayout = new javax.swing.GroupLayout(PanelHorario);
        PanelHorario.setLayout(PanelHorarioLayout);
        PanelHorarioLayout.setHorizontalGroup(
            PanelHorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHorarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHora)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        PanelHorarioLayout.setVerticalGroup(
            PanelHorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHorarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelHorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHora)
                    .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelTaxiRLayout = new javax.swing.GroupLayout(PanelTaxiR);
        PanelTaxiR.setLayout(PanelTaxiRLayout);
        PanelTaxiRLayout.setHorizontalGroup(
            PanelTaxiRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTaxiRLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(PanelTaxiRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelTaxiRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDireccionOrigenT)
                    .addComponent(txtTelefonoT)
                    .addComponent(cmbOrigenT, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreT, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PanelHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTaxiRLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(PanelTaxiRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelTaxiRLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(PanelTaxiRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelTaxiRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDireccionDestinoT, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbDestinoT, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelTaxiRLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCntAutos, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(235, Short.MAX_VALUE))
        );
        PanelTaxiRLayout.setVerticalGroup(
            PanelTaxiRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTaxiRLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelTaxiRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelTaxiRLayout.createSequentialGroup()
                        .addGroup(PanelTaxiRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtNombreT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelTaxiRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbOrigenT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelTaxiRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtDireccionOrigenT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(PanelHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelTaxiRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtTelefonoT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelTaxiRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cmbDestinoT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelTaxiRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDireccionDestinoT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelTaxiRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtCntAutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        PanelTaxiP.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos chofer", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        PanelTaxiP.setForeground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Nombre:");

        cmbNombreTaxi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbNombreTaxi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/taxi-chico.png"))); // NOI18N

        javax.swing.GroupLayout PanelTaxiPLayout = new javax.swing.GroupLayout(PanelTaxiP);
        PanelTaxiP.setLayout(PanelTaxiPLayout);
        PanelTaxiPLayout.setHorizontalGroup(
            PanelTaxiPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTaxiPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbNombreTaxi, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(27, 27, 27))
        );
        PanelTaxiPLayout.setVerticalGroup(
            PanelTaxiPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTaxiPLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelTaxiPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(PanelTaxiPLayout.createSequentialGroup()
                        .addGroup(PanelTaxiPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel10)
                            .addComponent(cmbNombreTaxi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)))
                .addGap(9, 9, 9))
        );

        btnGuardarT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGuardarT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/save (1).png"))); // NOI18N
        btnGuardarT.setToolTipText("Guardar datos");
        btnGuardarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarTActionPerformed(evt);
            }
        });

        btnSalirT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSalirT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/log_out.png"))); // NOI18N
        btnSalirT.setToolTipText("Salir de Taxi Pedido");
        btnSalirT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PanelTaxiR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PanelTaxiP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGuardarT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSalirT)
                        .addGap(25, 25, 25))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelTaxiR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PanelTaxiP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnGuardarT, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSalirT, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirTActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        frmPrincipalTaxi pt=new frmPrincipalTaxi();
        pt.setVisible(true);
    }//GEN-LAST:event_btnSalirTActionPerformed

    private void btnGuardarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarTActionPerformed
        // TODO add your handling code here:
        if (txtNombreT.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese el nombre del pasajero");
        } else {
            nombrePasajeroT = txtNombreT.getText();
            if (cmbOrigenT.getSelectedItem().equals("")) {
                JOptionPane.showMessageDialog(null, "Escoja un barrio de Origen");
            } else {
                barrioOrigenT = String.valueOf(cmbOrigenT.getSelectedItem());
                if (txtDireccionOrigenT.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Ingrese la direccion de origen");
                } else {
                    direccionOrigenT = txtDireccionOrigenT.getText();
                    if (txtTelefonoT.getText().equals("")) {
                        JOptionPane.showMessageDialog(null, "Ingrese u telefono de contacto del pasajero");
                    } else {
                        telefonoT = txtTelefonoT.getText();
                        if (cmbDestinoT.getSelectedItem().equals("")) {
                            JOptionPane.showMessageDialog(null, "Escoja el barrio de destino");
                        } else {
                            barrioDestinoT = String.valueOf(cmbDestinoT.getSelectedItem());
                            if (txtDireccionDestinoT.getText().equals("")) {
                                JOptionPane.showMessageDialog(null, "Ingrese la direccion de destino");
                            } else {
                                direciconDestinoT = txtDireccionDestinoT.getText();
                                if (txtCntAutos.getValue()<=0) {
                                    JOptionPane.showMessageDialog(null, "Ingrese al menos 1 auto");
                                } else {
                                    cantAuto = String.valueOf(txtCntAutos.getValue());
                                    if (txtHora.getText().equals("")) {
                                        JOptionPane.showMessageDialog(null, "Ingrese la hora de recojida");
                                    } else {
                                        horaT = txtHora.getText();
                                        if (cmbNombreTaxi.getSelectedItem().equals("")) {
                                            JOptionPane.showMessageDialog(null, "Escoja el chofer");
                                        } else {
                                            nombreT = String.valueOf(cmbNombreTaxi.getSelectedItem());
                                            JOptionPane.showMessageDialog(null, "La reserva quedo registrada");
                                            BorrarTexto();
                                            cmbOrigenT.setSelectedIndex(-1);
                                            cmbDestinoT.setSelectedIndex(-1);
                                            cmbNombreTaxi.setSelectedIndex(-1);
                                            txtCntAutos.setValue(0);
                                        }
                                    }
                                    
                                }
                            }
                        }
                    }
                }
            }
        }
        
        
    }//GEN-LAST:event_btnGuardarTActionPerformed

    private void txtHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoraActionPerformed

    public void BorrarTexto(){
    
        txtNombreT.setText("");
        cmbOrigenT.setSelectedIndex(-1);
        txtDireccionOrigenT.setText("");
        txtTelefonoT.setText("");
        cmbDestinoT.setSelectedIndex(-1);
        txtDireccionDestinoT.setText("");
        txtCntAutos.setValue(0);
        txtHora.setText("");
        cmbNombreTaxi.setSelectedIndex(-1);
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTaxiR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTaxiR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTaxiR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTaxiR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTaxiR().setVisible(true);
            }
        });
    }
    
     DefaultComboBoxModel modeloBarriosOrigen=new DefaultComboBoxModel();
     DefaultComboBoxModel modeloBarriosDestino=new DefaultComboBoxModel();
     //Declaracion para futuro salva de los valores capturados
     String nombrePasajeroT;
     String barrioOrigenT;
     String direccionOrigenT;
     String telefonoT;
     String barrioDestinoT;
     String direciconDestinoT;
     String cantAuto;
     String horaT;
     String nombreT;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelHorario;
    private javax.swing.JPanel PanelTaxiP;
    private javax.swing.JPanel PanelTaxiR;
    private javax.swing.JButton btnGuardarT;
    private javax.swing.JButton btnSalirT;
    private javax.swing.JComboBox cmbDestinoT;
    public static javax.swing.JComboBox cmbNombreTaxi;
    private javax.swing.JComboBox cmbOrigenT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblHora;
    private com.toedter.components.JSpinField txtCntAutos;
    private javax.swing.JTextField txtDireccionDestinoT;
    private javax.swing.JTextField txtDireccionOrigenT;
    private javax.swing.JFormattedTextField txtHora;
    private javax.swing.JTextField txtNombreT;
    private javax.swing.JTextField txtTelefonoT;
    // End of variables declaration//GEN-END:variables
}
